### PR TITLE
feat: support DDEV environment-specific ports

### PR DESCRIPTION
**Pull request by lemachinarbo**
- Added `DDEV_ROUTER_HTTP_PORT` and `DDEV_ROUTER_HTTPS_PORT` support.
- Checks both HTTP and HTTPS, prioritizing HTTPS.
- Switched 404 check to 200.

### CODE REVIEW

**Comment by BernhardBaumrock** [comment]
GREAT! Thank you :)

**Comment by BernhardBaumrock** [comment]
@lemachinarbo 

I think this PR could get some fine-tuning...

image

This seems fine, but then:

image

image

Which should only be calendar.ddev.site, no?

**Comment by lemachinarbo** [comment]
Indeed! I'm always using DDEV custom ports, so I never tested the default version with default ports! 🤦
Here's a PR: https://github.com/baumrock/RockShell/pull/20

**Comment by BernhardBaumrock** [comment]
Great, thx! Already had a glance and looks good so I'll merge it tomorrow :)

**Pull request merged**
